spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ee-test
    username: postgres
    password: 1234