spring:
  application:
    name: EventEase-backend
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ee-db
    username: postgres
    password: 1234
    flyway:
      baseline-on-migrate: true
