spring:
  application:
    name: EventEase-backend
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    flyway:
      baseline-on-migrate: true
